version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "18:00"
      timezone: Asia/Singapore
    groups:
      dependencies:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /
    ignore:
      - dependency-name: numpy
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
      time: "18:00"
      timezone: Asia/Singapore
    groups:
      dependencies:
        patterns: ["*"]
