[tool.pylint.format]
good-names = ['x', 'y', 'z', 'i', 'id', 'ok']

[tool.pylint.messages_control]
disable = [
    'missing-module-docstring',
    'no-name-in-module',
    'useless-import-alias',
    'line-too-long',
    'too-many-arguments',
    'too-few-public-methods',
]

[tool.pyright]
stubPath = 'server/typings'
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poetry]
name = "CapGen"
version = "0.1.0"
description = ""
authors = ["winstxnhdw <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
faster-whisper = "^0.9.0"
nvidia-cudnn-cu11 = { version = "^8.9.4.25", optional = true }
nvidia-cublas-cu11 = { version = "^11.11.3.6", optional = true }

[tool.poetry.group.server.dependencies]
supervisor = "^4.2.5"
fastapi = "^0.103.2"
python-multipart = "^0.0.6"
hypercorn = "^0.14.4"
uvloop = "^0.18.0"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.331"
pylint = "^3.0.1"
pytest = "^7.4.2"
ruff = "^0.0.292"
httpx = "^0.25.0"

[tool.poetry.extras]
cuda = ["nvidia-cudnn-cu11", "nvidia-cublas-cu11"]

[tool.poetry.scripts]
capgen = "capgen:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
