[tool.pylint.format]
good-names = ['x', 'y', 'z', 'i', 'id', 'ok']

[tool.pylint.messages_control]
disable = [
    'missing-module-docstring',
    'no-name-in-module',
    'useless-import-alias',
    'line-too-long',
    'too-many-arguments',
    'too-few-public-methods',
]

[tool.pyright]
stubPath = 'server/typings'
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poetry]
name = "CapGen"
version = "0.1.0"
description = ""
authors = ["winstxnhdw <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
faster-whisper = "^1.0.2"
nvidia-cudnn-cu12 = { version = "^9.1.1.17", optional = true }
nvidia-cublas-cu12 = { version = "^12.5.2.13", optional = true }

[tool.poetry.group.server.dependencies]
supervisor = "^4.2.5"
fastapi = "^0.111.0"
pydantic-settings = "^2.2.1"
python-multipart = "^0.0.9"
gunicorn = "^22.0.0"
uvicorn = "^0.29.0"
httptools = "^0.6.1"
uvloop = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.364"
pylint = "^3.2.2"
pytest = "^8.2.1"
ruff = "^0.4.4"
httpx = "^0.27.0"

[tool.poetry.extras]
cuda = ["nvidia-cudnn-cu12", "nvidia-cublas-cu12"]

[tool.poetry.scripts]
capgen = "capgen:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
