[tool.pylint.format]
good-names = ["x", "y", "z", "i", "id", "ok"]

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "no-name-in-module",
    "useless-import-alias",
    "line-too-long",
    "too-many-arguments",
    "too-few-public-methods",
]

[tool.pyright]
stubPath = "server/typings"
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poetry]
name = "CapGen"
version = "0.1.0"
description = ""
authors = ["winstxnhdw <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
faster-whisper = "^1.0.3"
nvidia-cudnn-cu12 = { version = "8.9.7.29", optional = true }
nvidia-cublas-cu12 = { version = "^12.5.3.2", optional = true }

[tool.poetry.group.server.dependencies]
supervisor = "^4.2.5"
granian = "^1.5.2"
litestar = "^2.10.0"
pydantic-settings = "^2.4.0"
python-multipart = "^0.0.9"
uvicorn = "^0.30.4"
uvloop = "^0.19.0"
numpy = "<2.0.0"
picologging = "^0.9.3"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.374"
pylint = "^3.2.6"
pytest = "^8.3.2"
ruff = "^0.5.5"
httpx = "^0.27.0"

[tool.poetry.extras]
cuda = ["nvidia-cudnn-cu12", "nvidia-cublas-cu12"]

[tool.poetry.scripts]
capgen = "capgen:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
