[tool.pylint.format]
good-names = ['x', 'y', 'z', 'i', 'id', 'ok']

[tool.pylint.messages_control]
disable = [
    'missing-module-docstring',
    'no-name-in-module',
    'useless-import-alias',
    'line-too-long',
    'too-many-arguments',
    'too-few-public-methods',
]

[tool.pyright]
include = ['server']
stubPath = 'server/typings'
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poetry]
name = "CapGen"
version = "0.1.0"
description = ""
authors = ["winstxnhdw <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
faster-whisper = "^0.8.0"

[tool.poetry.group.server.dependencies]
fastapi = "^0.103.1"
hypercorn = "^0.14.4"
python-multipart = "^0.0.6"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.327"
pylint = "^2.17.5"
pytest = "^7.4.2"
isort = "^5.12.0"
httpx = "^0.25.0"
