name: Build

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/build.yml
      - Caddyfile
      - supervisord.conf
      - Dockerfile.build
      - pyproject.toml
      - poetry.lock
      - .dockerignore
      - server/**
      - tests/**
      - capgen/**

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/python.yml@main

  build:
    uses: winstxnhdw/actions/.github/workflows/docker-push.yml@main
    secrets: inherit
    permissions:
      packages: write

  restart:
    needs: [test, build]
    uses: winstxnhdw/actions/.github/workflows/spaces-restart.yml@main
    secrets: inherit
