name: Dependabot

on: pull_request

permissions:
  contents: write

jobs:
  test:
    uses: winstxnhdw/CapGen/.github/workflows/main.yml@main

  auto-merge:
    needs: test
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Auto-merge Dependabot PRs
        run: gh pr merge --auto --rebase $PR_URL
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
