name: Dependabot

on: pull_request

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/python.yml@main

  auto-merge:
    needs: test
    uses: winstxnhdw/actions/.github/workflows/dependabot-public.yml@main
    secrets: inherit
    permissions:
      contents: write
