name: Dependabot

on: pull_request

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the Docker containers
        run: docker build -t $TAG .
        env:
          TAG: ${{ github.event.repository.name }}

  auto-merge:
    needs: build
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Auto-merge Dependabot PRs
        run: gh pr merge --auto --rebase $PR_URL
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
