name: Deploy

on:
  push:
    branches: main
    paths: Dockerfile

jobs:
  deploy:
    uses: winstxnhdw/actions/.github/workflows/spaces-deploy.yml@main
    secrets:
      token: ${{ secrets.HF_TOKEN }}
