name: Deploy

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/main.yml
      - Dockerfile

jobs:
  deploy:
    uses: winstxnhdw/actions/.github/workflows/spaces-deploy.yml@main
    secrets:
      token: ${{ secrets.HF_TOKEN }}
