from collections.abc import Iterable, Iterator
from typing import Protocol

class Segment(Protocol):
    @property
    def id(self) -> int: ...
    @property
    def start(self) -> float: ...
    @property
    def end(self) -> float: ...
    @property
    def text(self) -> str: ...

def segments_to_srt(segments: Iterable[Segment]) -> Iterator[str]: ...
def segments_to_vtt(segments: Iterable[Segment]) -> Iterator[str]: ...
